### ISSUE TITLE
Declare CUDA-suffixed dependencies in pyproject.toml

### ISSUE THREAD

**Issue by bdice** [vyasr/rapids_builder#1]
### Option 1

Currently there are some lists of packages requiring suffixes in `build.py`.

https://github.com/vyasr/rapids_builder/blob/b67aa15dbdf5a81bb0b7c251540b7e292b3c4413/rapids_builder/build.py#L94-L132

It seems like it could be better to have multiple tables of dependencies, rather than specifying this in this repository's source code.

The `[build-system.requires]` could list "normal" dependencies and the `[tool.rapids_builder.requires]` could list suffixed dependencies. However, `cupy` and packages that are specific to a CUDA major version (like `ptxcompiler`, `cubinlinker`, `pynvjitlink`) might still need special treatment.

**My primary goal is to avoid relying on a central listing of all suffixed packages**. If we do rely on a centralized list, then adding a new package to the RAPIDS ecosystem means that we must change the `rapids_build` package at the same time. The builder must not require changes to add new packages to the RAPIDS ecosystem, as we intend for the builder to be public / OSS and we might need to reference internal or private package names. This is also essential for the builder to be reusable by non-RAPIDS users.

Perhaps only the special cases need to be handled in `rapids_build` and everything else can be assumed to use RAPIDS defaults of `-cu11`, `-cu12` with support on both CUDA 11/12?

--------------------------

### Option 2

We could include the specifiers in the TOML itself, under the key `tool.rapids_build.cuda_options.{{ PACKAGE }}`. That key would have optional entries for `suffixes` (defaults to `{11: "-cu11", 12: "-cu12"}`) and `supports` (defaults to `[11, 12]`).

Forgive my use of TOML, I might have an error. Hopefully this conveys the idea.

```toml
[build-system]
build-backend = "rapids_builder"
requires = [
    "cmake>=3.26.4",
    "cython>=3.0.3",
    "ninja",
    "numpy==1.23.*",
    "protoc-wheel",
    "pyarrow==14.0.2.*",
    "rmm==24.4.*",
    "scikit-build-core[pyproject]>=0.7.0",
]

[tool.rapids_builder]
build-backend = "scikit_build_core.build"
commit-file = "cudf/_version.py"
cuda_requires = [
    "cubinlinker",  # Filtered out for CUDA 12 because `12` is not in `tool.rapids_builder.cuda_options.cubinlinker.supports`
    "cupy",         # This uses custom suffixes like -cuda12x
    "ptxcompiler",  # Filtered out for CUDA 12 because `12` is not in `tool.rapids_builder.cuda_options.ptxcompiler.supports`
    "pynvjitlink",  # Filtered out for CUDA 11 because `11` is not in `tool.rapids_builder.cuda_options.pynvjitlink.supports`
    "rmm",          # This uses the default settings
]

[tool.rapids_builder.cuda_options.cubinlinker]
supports = [11]

[tool.rapids_builder.cuda_options.ptxcompiler]
supports = [11]

[tool.rapids_builder.cuda_options.pynvjitlink]
supports = [12]

[tool.rapids_builder.cuda_options.cupy.suffixes]
# Override the suffixes for cupy
11 = "-cuda11x"
12 = "-cuda12x"

# Manually writing the default values for rmm here, to illustrate the syntax -- this would not be needed, by default
[tool.rapids_builder.cuda_options.rmm]
supports = [11, 12]

[tool.rapids_builder.cuda_options.rmm.suffixes]
11 = "-cu11"
12 = "-cu12"
```

**Comment by trxcllnt** [comment]
Can we use a template and string interpolation instead?

```toml
cuda_requires = [
    "cubinlinker-cu{cuda_major}",
    "cupy-cuda{cuda_major}x",
    "ptxcompiler-cu{cuda_major}",
    "pynvjitlink-cu{cuda_major}",
    "rmm-cu{cuda_major}",
]
```

That way we could also support names with major/minor/patch later if necessary.

**Comment by bdice** [comment]
Here's a more concise form of Option 2. Wow, TIL a lot of TOML.

```toml
[tool.rapids_builder.cuda_options]
cubinlinker.supports = [11]
ptxcompiler.supports = [11]
pynvjitlink.supports = [12]
# Override the suffixes for cupy
cupy.suffixes = {'11' = '-cuda11x', '12' = '-cuda12x'}
# Manually writing the default values for rmm here, to illustrate the syntax -- this would not be needed, by default
rmm.supports = [11, 12]
rmm.suffixes = {'11' = '-cu11', '12' = '-cu12'}
```

I would be okay with string interpolation for the suffixes but we still need a way to indicate the supported major versions so we can filter out CUDA 11-only/12-only packages.
